#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
VUNDLE_DIR="vim/bundle/Vundle.vim"
TPM_DIR="tmux/plugins/tpm"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

git -C "${VUNDLE_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${VUNDLE_DIR}"

vim +PluginInstall +qall

git -C "${TPM_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${TPM_DIR}"

