set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

Plugin 'wilsaj/chuck.vim'

Plugin 'tomtom/tcomment_vim'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()
filetype plugin on
filetype plugin indent on

" colorscheme for gui and terminal
if has("gui_running")
  set background=light
  colorscheme white-sand

  set guioptions -=m     " remove menubar
  set guioptions -=T     " remove toolbar
else
  set background=dark
  colorscheme white-sand
endif
syntax enable

set noswapfile
set encoding=utf-8

" tabs and spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

autocmd Filetype python setlocal ts=4 sw=4 sts=4 et

set autoindent
set smartindent


" ui options
set relativenumber
set cursorline
set scrolloff=3

set wildmenu

set showmatch

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=80


" leader etc.
let mapleader = ","

inoremap jj <esc>
nnoremap ; :
vnoremap ; :

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>


" search options
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch

set hlsearch
nnoremap <leader><space> :nohlsearch<CR>

" movement
nnoremap j gj
nnoremap k gk

nnoremap E $
nnoremap B ^


" autocommands
au FocusLost * :wa                    " save buffer when loosing focus
au BufWritePre * :%s/\s\+$//e         " remove trailing whitespaces
